on:
  - push
  - pull_request

jobs:
  compile-examples:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        fqbn:
          - arduino:avr:micro
          - arduino:avr:nano
          - arduino:avr:mega

    steps:
      - uses: actions/checkout@v3
      - uses: arduino/compile-sketches@v1
        with:
          fqbn: ${{ matrix.fqbn }}

          sketch-paths: |
            - examples/test_one
            - examples/test_two
